apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi-controller
  namespace: unifi
spec:
  interval: 5m
  chart:
    spec:
      chart: unifi
      version: "5.1.2"
      sourceRef:
        kind: HelmRepository
        name: geek-cookbook
        namespace: flux-system
  values:
    image:
      repository: linuxserver/unifi-controller
      tag: latest
      pullPolicy: IfNotPresent
    persistence:
      data:
        enabled: true
        accessMode: ReadWriteMany
        size: 10Gi
    

    env:
      TZ: "America/Chicago"
      PUID: "568"
      PGID: "568"

    service:
      main:
        ports:
          http:
            enabled: true
            port: 8080
          https:
            enabled: true
            port: 8443
          portal:
            enabled: true
            port: 8880
          portal-ssl:
            enabled: true
            port: 8843

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: unifi.local
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: unifi-tls
            hosts:
              - unifi.local

    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet 