apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helm-repository.yaml
  - mongodb-helm-repository.yaml
  - mongodb-sealed-secret.yaml
  - mongodb-helm-release.yaml
  - helm-release.yaml