apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-mongodb-init
  namespace: unifi
data:
  init-unifi.sh: |
    #!/bin/bash
    set -e
    mongosh admin --eval "
      db.createUser({
        user: 'unifi',
        pwd: '$MONGO_USER_PASSWORD',
        roles: [
          { role: 'dbOwner', db: 'unifi' },
          { role: 'dbOwner', db: 'unifi_stat' },
          { role: 'dbOwner', db: 'unifi_audit' }
        ]
      });
    "
