apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi-mongodb
  namespace: unifi
spec:
  interval: 1h
  chart:
    spec:
      chart: community-operator
      version: "0.10.0"
      sourceRef:
        kind: HelmRepository
        name: mongodb
        namespace: unifi
  values:
    # MongoDB Community Operator configuration
    replicas: 1
    
    # Security context
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 2000
    
    # Resource limits for the operator
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 500m
        memory: 500Mi