apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-mongodb-init
  namespace: unifi
data:
  init-unifi.sh: |
    #!/bin/bash
    set -e
    DECODED_PASS=$(python3 -c "import urllib.parse, os; print(urllib.parse.unquote(os.environ['MONGO_USER_PASSWORD']))")
    mongosh admin \
      -u "$MONGO_INITDB_ROOT_USERNAME" \
      -p "$MONGO_INITDB_ROOT_PASSWORD" \
      --eval "
        db = db.getSiblingDB('unifi');
        db.createUser({
          user: 'unifi',
          pwd: '$DECODED_PASS',
          roles: [
            { role: 'dbOwner', db: 'unifi' },
            { role: 'dbOwner', db: 'unifi_stat' },
            { role: 'dbOwner', db: 'unifi_audit' }
          ]
        });
      "
