---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unifi-mongodb-secret
  namespace: unifi
spec:
  encryptedData:
    mongodb-password-urlencoded: AgB+VBrozcT3ikO4ylPwmX2NabtDVDNzrSC7XaTJWdT2/tbKVaiZomlOQ8SsPS/MK0xO9FcP+v4P+CwBm7WJNbNUiyhdukdQHBY6neKce7sz/KUDwtmBGUW1vyy+VmzTC8tZqQdOvlD4JP+ydXgHbDjPJd2JRHkEqPpzj/mIO3NYmfTt6DCrNrPSwgpkkvlMNuwlj2aVOP6V5LyPoHHnOjLy2jo9t9mNdWB2WY8dG3dlS6zVy9qvxx78adrmLkuvbLy09sR4KBDA/+LUR6RsQfjt4rQwvpDRLzMyMhd6Fp1ZsSauNEbURzk+KytdV+wCJc6kq3qLmvaiNbPymqCfF+rL0DtmqPo4R9t3C1p3k2vS7CfA7qgbwLpKpDcpdJf9fKcCyuDn89MUr2vLQyJ5NVV+qzi7RITroGn/4zdPV7BEqWiqFFDzbx66Jb0wg0hlSE98D/JG/gvO+qbjWM+o9RYCb70YIEFnKjCrIItf4J9pOBK+n+uCKJW9IjvwYQxRyqmg/qi5e1tw56pPKxo3Oi0z9F1vVcM74anE3Li9k2FUXtm8n1ggDGx0EmSdLWlYJbuVRyRvvL/RyHQld83M6ZGd7acoQ959v6m6kRNY7UxGxW+sd8BU5ylQesw3AtEiuEuKqVYjfQMXB0TktvGBDokX7k5rX6Iouq0QxALR/IttQ+zTXDAkfm+27gaEuySvcGMfM5YaOXNGsyTlADhCc96Ge+qz+5BUDhI=
    mongodb-passwords: AgARJ46FeLLOky8TQmb6aidrxaU5FCB2ZG3VLhXgN1sd3ichY2N9wfOj2DRsfz/8FvrTUCtwFbiiQbSYfwH1rbzLMTP7SQ0NKbefzVVmQJeulQ46b32uRsM0B+uIqL2kUzgNs8s2DQkYN6+LJwX5tEfS55PQPYX4YfY7v89zNnTZvbtfAq+JtmXC5yxs5JTr8bo9dnWTMkkVxt8o8P6LlC8FXS0AVzc4yVuJ/MWhdMftV9DcwfMPjUXOtUA1/iJGo5dKBYP+4KJ0AMpKxIHHI9g8/lAeY0gKXMMeFzXlnX4cXmkFKRqqqnqpn17NVPycBPrmhDbzQt1gIERP4Ew6XsfhJyv3m/JiFlK3/IYQh5TzHH2Td8KgP1ESQj4IMhYb+jqLpr5ymzCn9hJWtCkQDj8TWE8qHlM0tnXXAWebVjn/fhcHc6opWxLWKSTfTyijYl1ZSPW1Dkir5hv7rifzcs5+T/YGoQNWVyBKiy4k4SHHz+LR4JoFUd6juqHh3dm4AOR2HH3501RFalaRnf3Kg67Wlpy7Lsvf/N+AS2lYAhNGYG+PrYFk+1zSpdg28sIiWgkxaJOK5H1pvW7sSjObSSpNBw92snoHlDTcznFcg/k17exts0+NcPi0u8RjWLluF5s4z4ppQ+sOJNJ0B/f89MVThf6owCoZ3JKHrv7Y9GnrjeLKRd+tDFFzLBz3YhzvPNOHWNTmcxKX3Dgkf0ebdGlSnlcjl1txNm5waDE8cvPJHizNEvZS+PfASw==
  template:
    metadata:
      creationTimestamp: null
      name: unifi-mongodb-secret
      namespace: unifi
    type: Opaque
