apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi-mongodb
  namespace: unifi
spec:
  interval: 1h
  chart:
    spec:
      chart: mongodb
      version: "14.1.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: unifi
  values:
    global:
      storageClass: "nfs-client"
    architecture: standalone
    auth:
      enabled: true
      database: unifi
      username: unifi
      password: ""
      existingSecret: "unifi-mongodb-secret"
    primary:
      extraEnvVars:
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: unifi-mongodb-secret
              key: mongodb-root-password
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: unifi-mongodb-secret
              key: mongodb-passwords
      persistence:
        enabled: true
        accessModes:
          - ReadWriteMany
        size: 8Gi
        annotations:
          nfs.io/createUID: "1001"
          nfs.io/createGID: "1001"
          nfs.io/createMode: "0755"
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1Gi
    service:
      type: ClusterIP
      ports:
        mongodb: 27017 