---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-credentials
  namespace: frigate
spec:
  encryptedData:
    CAMERA_PASSWORD: AgCwq4P0FGUoJ8yd+AyBpWjIGp1CcdewsPv+Ui0ejb3+qrGwUAWvRRxuouDAMUqZdAVfvCcNZ7YSBd3kpX+fXcY8cmTtJfxXAGc5iaUh+xWKtbRpt3piLPknuZpAudrW3ijlUiRjEvb0NtIiihtOAGRYKrDhNeNH6dxT3YVPTWIJlFOr7E++00poLHu7VNOrcC7YYF/VZhQwwL2fT6g6loTknx//oH/+S8rlP73yjCDzUhXm9acSVLHNleJ5bk55/T3IzNtiGhXagcNvtH9GeZGwaC/uqxHLa1UMTzL05VRZ6Za9lDnT6Cz2G5uaVRwZneY5FYquLxLYf7dD8rFamf4GdvKMpykYdId9BzMNX/Vl1u4Pe9KUa9RpBQEjvqtB6LPCYBXeAKvCUd+koLWMl0NQv3FXMj0+FJ6GHqh2W+A5wjmBWUwSVrWbGC7GPfPEO72bME7jNOhilk/9cCA9kjw7FB8HKZuiojCywm7FYBX2+O9Tp/w90brNr6lKPwtO5CXB8vyDwr+v4KY74rVOzbs1DBaMMseoV66MVpqMGKPQm5AJloOBTdVs1CmHOH3OvO379c5t3n6ilAGJNPcE1wvmXb5TTMK/DhjJY6sJ6Bu9KJf4vcIODzI5BE69P3vaVnai0+IFJqBryzAwkXNLQOCfD0UvD7cQJ7DJbcRte+GSWTG1LZhwiqutWCrEe9pewD6eK2it8XU4GKilhz0QsyY1CzZqhg==
  template:
    metadata:
      creationTimestamp: null
      name: frigate-credentials
      namespace: frigate
    type: Opaque
