---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-overnight-summary-secret
  namespace: frigate
spec:
  encryptedData:
    SLACK_BOT_TOKEN: AgAxc6oI3lbSZ7DbhhleHdfGvBXjM7bzvbXc814eZgcjyrlJBhsZFEf7wouGX/fOCu/cuQ7oDqFSRvjkl1a38UEPN+jKVaYhuGOiJre2LfQUF3ekaIKc78RSDJt5pEkbyaACpkTCuAD/gdwop+Y+R9iO35C1FnoUy6plAtlyADULZWEnBxDzGKtxLoRsYcMKS0BBnGrF/xtAIqpDSsYqDbAkfphasH6RIo4YybDZkkG03nqOmqF4mm7Ay4dXiQJdKxwiEccUMjHCSzj2H6de8/V7mA1BbawTJOcU25+1DSYv4R+fxdQ90OjWjFF+HNMH6AJenV7wKu4hAazF8Ei3r9KcnQV5l3JWsIdBIciFVHEJy8UcHnX939nPOsQD7Ob+2GSRV4vp3ptTeM/94OL+qSIBlOKQsn4tfLNZ9CoNtPOaN7OOVdaROXdIlaRPAlrjdSUAHTLD41rJqeUHbkBWx+eD6NX6TPdluy39D/z4DBvFhDkFlzTRX0jP65+l77SwIK7AYZRmT1Z0Xo33e1jTJj1vMRMTDSPDzjuhLa0Xt/6ZBdhL0y3Dp3kUPkZtq4SHTBCOeFsssVi3eUWcFnkZKfVFKFWxO7Oq3pB8kIL154Hgtt0P8trCLQiA8JlNjyN2mnMBwyGPOljTZFi1Y6qN7iguaPsylIoAiK05PGF+yA0M6f/Qb9rAtkoldnsY2bN1jm//o3l33lXt882C7nY1FMJt6o7dXvyvia61dubIZCL0kdvVUo0tpdtGnRRAkRl/mICfIbRnN3VbJeGG
  template:
    metadata:
      creationTimestamp: null
      name: frigate-overnight-summary-secret
      namespace: frigate
    type: Opaque
