---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-credentials
  namespace: frigate
spec:
  encryptedData:
    CAMERA_PASSWORD: AgBu6jp0ZbW90/NChDhibgCmvJo5BuLnJL/PPIG7GUb+CvP94sjL1ZiEYkGwFFnDrZmr/OtZuKvL3idsseM9ZHUxHLNymjzUu/CrTtLDtVv7nHbO5Ni49MELLortxVQiVpvYLh7Tf5NyTHJKWLYHasPd9sS/86/CSQ0KFCUAyHBaGTjQFG1ahl6mlM8U87oVcOWrtvOxVzypYt2yzKv09waS6aQ0Qv6l4A3Tznte/PyCbIDb9armiPEg2e8m64U7M3FTWU/KTgq/xssCnJQGCpg4juu9BUhth/iFOnfEHNgp7zV+/vTWoVAJT8/sJrJFjyIzFeraVeOQTPjuMArdaLJapFUvyeRDnkuxDY/jknhaCfXN02Z+jT9RFQyUduxpmi/cYwkMTNNxFv6lr92mI68AWH3l4/SK2HYobHfVgbrzgzcZ+iX4tfiLHv1pljpbro9RvanAdVhrrvb1/T/TpwGV7AFVsRTPEKbF9GxxRcUfCPxJD7vB8+Aw05lMVpVAI1OY5Q8A2WqJWiaDbAPLSs6IINx5hbz1w6bh/iItMXzNdscFPD9e63cMwywY5+ZXUS/NbH+yjrvtFdms09jYzFjE5CXfh++clwAwdF38Zi9WiR9PSx+8v+Ev4bQ9Cj17kVKsqXcIZOQ5A0KGmrBGCthIMnBSbO0VeDXXCtygRGLUnOc+OLH2aKTwzqOWMLj0dV77/rvxKc/6UNkQQewLArA=
  template:
    metadata:
      creationTimestamp: null
      name: frigate-credentials
      namespace: frigate
    type: Opaque
