---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-credentials
  namespace: frigate
spec:
  encryptedData:
    FRIGATE_RTSP_PASSWORD: AgC5Sw2hphvOH3ZcsYgy/1waXbO5s8rWPOWJPK5DIKr1Gi4Wk+SKPf+C9NOUI45n+upo212tmnR0KM3sbtHUiQhBWIO+Bw0mffUfxgN0P6p3Vns+sED+jnLJv7yOp66g75/g9ZURhqTwSWtOK4dWJAX6MVCAnQg9HQoFe9s/lNhqX2zaidWhnTOMOn1dVWPSD05pnmfnBo9egSIcncWxwJwS3Ti5LHS1j99q8xDLLElgkoAxNdNHmD+SAu50E3HIro7jz0bWIvJo8L993yaWVoMln0jHT13VyfHwZlyMHj+OPsyh3mRadzR4rxwPYsAYqf1lDtgUA78FRQNWVujpqL+z3bKTMxeZwEHXN7bH45SnT5VX8E2dxNZHS+rDKx+nMNjZpEUxwcuycYSOlqk10RrlSQD2zFk97S6nNu3nsrp2mSDOc5OnTVdBfGHQFRfgGK1jw9zNlNYGQvp123yuZKjlZlfnQZvqJ1NLJujl/i//pZJr4iRANxbhDJn0KzYUiIyuehNS5FzHYLUMbxSdxgWDspRaIktUYvePQF9025UnTY6hnlaUaLVBnmRcVKCbIUDC8PfNdBiYeCXUbkKw6mM36C9zfwTLEbNRRq4l1oXcYbL90GzaN5PQ7AjFiBhPG091JHAFlmdU3415OuBm5Ji5MUiCYTY8WTKrLvay3bCFJo75MiPuZlQmWOyrCypnssuPIEihVDXmX03a4hTF0yMKdmOKsA==
  template:
    metadata:
      creationTimestamp: null
      name: frigate-credentials
      namespace: frigate
    type: Opaque
