apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-report-config
  namespace: monitoring
data:
  PIHOLE_URL: "http://192.168.86.53"     # UPDATE with PiHole RPi address
  CLIENT_IP: "192.168.86.32"              # UPDATE with Chromebook's static IP
  DEVICE_NAME: "Chromebook"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-report-pc-config
  namespace: monitoring
data:
  PIHOLE_URL: "http://192.168.86.53"     # UPDATE with PiHole RPi address
  CLIENT_IP: "192.168.86.35"              # UPDATE with PC's static IP
  DEVICE_NAME: "PC"
