apiVersion: batch/v1
kind: CronJob
metadata:
  name: dns-report
  namespace: monitoring
spec:
  schedule: "0 21 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 300
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: dns-report
              image: ghcr.io/cjchand/generate-dns-report:latest
              envFrom:
                - configMapRef:
                    name: dns-report-config
                - secretRef:
                    name: dns-report-secrets
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 200m
                  memory: 128Mi
