---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dns-report-secrets
  namespace: monitoring
spec:
  encryptedData:
    PIHOLE_PASSWORD: AgAz7ZJEVw6qnpQD97J8fKlq/yfD+f5Lu0rKpGoNRolkP1dclwe0MoISbnn1PIkbrwr8wyH431yiT2xiSg5RsJrYQ/nc3B0hTQTJ9PnBhYLo7VHXJl8mq/mUc3zHSgkb+K8sbXUSeZHw2lwsw7Qk0oqwcqMqYJD8p0NZ9pqQdLvX1l68t4HjfbGTPSB++ZLw7ccTNaH56hgz1sDmxK5L0LQqs+zydjzR9ik4lrnmHL7+qJV5q6I7gHUp5/OFZtdY/j9fXjUC95QP7HcIUwONJmvTqyiUnHSJYqgsAg9LLfHjtC3362W58SpXWp997OXvm5JO6g25U25Diyn+EsO2AmjxjyvqBj+/DdPdgCCRa/TUm5lwTOYLI4xNOw0gG2Xvx8vBUnraj8BwPNGJaDDGvx4XBm1PPFnkjfN/V4TqB0Dtt0594nR8V7pnM+3XCmgARyFW5zn5pPEkNwG/Sr+0ziNY931zi1961aU8ldp7Sh1ryNy7BoNsP3ZQbFObDgtY00HMURN53TAx+IeFBed62U3HBPPwXoYbfFU1muyByeMBS6aa4Csbdvpql5lOleOSUoDzxqSdt+uDngUtNpHS0GRt9p2LmEAXjh1KhEUKUfQGT2rrqcesxH0ZXUNXRQaq6ebZY1PKGeXG2JhZWGjZ0zlF4zosr+iv+EWuGfTnlRCTk4OmXwjYJuNp/ss6xcq6xgbmGiPCc5xIyrJivL9qEiXYgzovRRZuTx9lE1ajMYvaYOMrf2em9xmN1d5Ilw==
    SLACK_WEBHOOK_URL: AgAsmk7bKwu/+irbqJYxQdrEG2d8jDVnRePSiphG4XrpooSRgXc86df2s74nb9zayengXQjk7V+H90pabSSOXk2r2I0J0RSUwm8FAoCcn1uE+SZnEgx5YDYrs34+dW8R9zrfeLujLShrpH65Y47moMcGr5CniCRqAUoK7eZTA1nAQqMYgEBUZjmL6NZ17zTS5N5UR5Lb4GHTee9oAp76RpApN+ELHiK6V5rc9yMk/3wBgSWpQAppvsiNj50XEwm4ndrl31FEusPTW2a5GvtlMkNi/5AoMOv3RkfiRI+G2lDVcHfaZqscZF+OIODTB23e1Vnpdq1sEZ6HijkjAjdSHxoOOmp9CLi27Ga5W38iTwnSWT/PLb1QtUZFrb7iYqc50q0rMtVGV1KS8LDeKNyqLsrpiJ3e0m+wBeDrFmop4OExk4zOEFXvgwF9cQRy31nc9N/eW2xjiB9QGdUXmSEvajVq6HaiYDJjeaW2zgUcu4pPs7SmsvZ7DHQe0azX30hjgFKHISX+0v4WzexROl+oSSc8XoXmp3Z2gEK+EH6ksO52TetnwwH4KzyqNgnQ9G6ALK2PLX98Ghnlg674riRCKbuQfHP4TebCah+LaAPtVzFxS18f8AR9ATPyGPLPO15EqWtPFahss0C10ROOEwW1+7A1XkLHezZ4x8JZOaD3U/LlWJ2egl5Hoe2jN/JNedq4AMPgb23r8kJ8/zKE+mrGp52HFf5/I5+4O25Jx+/1X47lZHrZV4XkGwo7Ub+iv7F6XskzUXR30CEu9PoD8nSv3aqixIqPAFzhZMR+ADpwd39MTLA=
  template:
    metadata:
      creationTimestamp: null
      name: dns-report-secrets
      namespace: monitoring
