---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: uptime-kuma
      version: 2.21.3
      sourceRef:
        kind: HelmRepository
        name: dieweil-uptime-kuma
        namespace: monitoring
  releaseName: uptime-kuma
  values:
    volume:
      enabled: true
      storageClass: nfs-client
      accessMode: ReadWriteMany
      size: 8Gi
    service:
      type: ClusterIP
      port: 3001
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
