---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBmf2il4fv48rB5TlTDnVMa/YLqBb35jXfSjTeVIVp5g6WFzvKn2k52ks4mQATq2QLHKGPCJKylo76SBVq6gkje9/HceRZbkr3kz/UhBFMMYut8SyNSmfG1bNA8ECtgelO/DIdDG0yiEEZvwntIPR4VIIsIqGy8D5zYu1k+P0SPN/c3LxVIIDX3NRRqt2ccLvMMzEUo1gYm1tv+ZnyAwktOkBPFklqKHxSIqZIRb5QBhenwP3+WBsYDulJcqKdykqyCoB8wF/0/kD8DZpmNFO8mqNOZVVoj3oyF7+4sSWrI/9NgxU7pQ3Aa64ZxF1blFbZjH02E4Y76pw41i+YHdFdHvQbH9evGC7CxHFGcYru/O3v5bN8fl+ciBfG3rLcwdnac/+DcGe99uv1pNIvD7LdGKqMw6E1P3/WYSDs5an6iK8xfV1VRh9bEp3PhXVieK5gh/AOAFqStNUckE4OusXBkPr3UPx2mnvvj4BLl2p5krojOS2CfDHQNH3d50dxzaKtVDjKSDaFBWHwMehMsytuabF/7xtkC8ns8tRNoxC9P2tuCjMYkEMcBRfcD8dOpi+oT8C76OnGFzFjpiWeyAiNlkBbDFcFPaaKPMcm3Gyq4cKaXQLjSI7Iuu4C/lyqAr32RhGGoRMt9ixBB1xTCmttwW6XXHWAAYhliIxkxTms9ZXjjqh9kG0pPzMgZOepd1voN96m9bqIRe/CSXR6f3GdzB2xouLA3JLY=
    admin-user: AgCzs4OH4tdPrgCTaI2EeCaFLTPjmJaJEfJkLJbXQB1W78jaRVJxqqEpNTy6bcIlri64w1BdoNrppna4f7UG4yRe6KMS9O2SLiXstkIziUsRNW+BeIQTHHXOxp5f9DJiyJ5ZHBlPHJakCYIs2Z987rE2msXvJL31pH9G3BtHsLq0IX2e3DBCt3+xzBeeQHins9HND1SdG6QFCVHanOExqTT51Q30s80DJ1gTX0QyjiAmm6F4BJ0BTMtuFC4gYwRlrgeU44CTmZpVP4xpSbmZa/xUpflwhTDvODCwbcKFd351VXnyEP57+hcMCJwGkbzBlBRNAOW6sksiKU4+Fzd5Pd6AUH6H8XYXqn053O7izuOXZhNswxgpZFvkFrk+vppV7alzYWxNqSzybCCyeUIpt+7Mfv2xgiRhjyZVPZQWk7Pa5wWvTGsVbE7oX+0fVMxC3Nr2M7xZq0/2mHJ0+OdAzw/3aVVTmJUQgOMlSxCh3Rumun0kMG9Y036bKplLLFqCOoz/2KuEfPcK1qKyXH+QCkn6T48qn3TS4eAL6S34l9m/Y2iiEJASb/6i0uq7p1ZykoZ16/2RKXEh1Cx1Xqs2gFS1G+S3DTYkEm7ciJY/+0boKszS/gXdFUkFalbnq/CoVLB2qmYfQa76Rsnf8SWHO8C133DbYCXKi7OL9hf1/LxFli+qngTCs0OQTUrM+EfPrw4oHtsU9w==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
