---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-slack-webhook
  namespace: monitoring
spec:
  encryptedData:
    slack_webhook_url: AgB0+WkDsu4VEX5GnAkp85/8y+/EtrKuHj6WrownxCsv/sGyBkGTMjmN4lVpimZg61SC8aI9VeyyZzlvwPb0uQEq8e+46SdNQczM5eUF2XwMGqZRzgkiCjyEaiSYk3GkLvlPVs5RVexivu9mOd86oVH+l3gQDkq060GifEZZY4WKZpc8B9qqJ1swKsBH5zNsTZXgaxgMr/A/FyGUDPFucUQflz5I9X7Pi8wo+ALXeRHV0JBEUA01NiTuTP0k3krUO5jzAP6B5SllZVNUJTUfEgoU6SCKFlbiux28yqEVFVkMAOJNTqobjhyRh9XfDu511zbv5gRQ8cF2JWw09wIbPturE2ENc+CVRSFVlUN27VcSijPMZTAH70CiIKhpeRCJRdXac7B2gBmJNyH9KghPSEt+PVjCBp/k8YsS0xZOpbGuYyhIJQv8nu/f7uMGSlnKZE84QVnb4snIpAgcWfi3coCC2lf6tT7uJvkBmpJne5wMmlCdnBsNnc3ql4dOMiLh2XWQeJ8/jWc4PSAgukmYtxjI6pVl1c6dfhSILsmHWWwtS9l8huaIdCeOgAxmvAIYw04nqjulv/nlmX134/TAaKeQuieURPwz/165OeJxbWyldrKRlocg9tIDHP0ehjCf1znIlUT+cEV3t3Ciom/CVFa6q59X28JBBJp/cgCfk39If1SZjW6EBIbAkY3/KSiKEPCKX/aesoEc5RMdYCaCwLBErK62qkf3/l8J1FKg1ezJ0nwJEuVcokZXWHrTycxXUKn4jG7/qdw3EnB/FthbDyi6+++ZCcfcQIY5by1ROM7+oxA=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-slack-webhook
      namespace: monitoring
    type: Opaque