apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-network-probe
  namespace: monitoring
spec:
  interval: 60s
  module: icmp
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:19115
  targets:
    staticConfig:
      static:
        - 192.168.86.1 # Google WiFi
        - 192.168.1.254 # AT&T Router
        - 8.8.8.8 # Google DNS
