apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      version: "v1.16.2"
  interval: 1h
  targetNamespace: cert-manager
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
    global:
      # Disable cert-manager validation webhook for namespace creation
      # This prevents chicken-and-egg problems
      leaderElection:
        namespace: cert-manager
    webhook:
      # Allow webhook to start even if cert-manager is not fully ready
      timeoutSeconds: 30
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

