apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/homepage
      version: "1.4.0"
      sourceRef:
        kind: GitRepository
        name: monsterrr
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: latest
      pullPolicy: IfNotPresent

    initContainers:
      - name: init-chown-data
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /app/config && chmod -R 755 /app/config"]
        volumeMounts:
          - name: config
            mountPath: /app/config

    volumes:
      - name: config
        persistentVolumeClaim:
          claimName: homepage-config
      - name: k8s-config
        configMap:
          name: homepage

    volumeMounts:
      - name: config
        mountPath: /app/config
      - name: k8s-config
        mountPath: /app/config/kubernetes.yaml
        subPath: kubernetes.yaml

    extraEnv:
      - name: HOMEPAGE_ALLOWED_HOSTS
        value: "homepage.internal"

    service:
      port: 3000
      targetPort: 3000

    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: homepage.internal
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: homepage-tls
          hosts:
            - homepage.internal 

    rbac:
      enabled: true

    serviceAccount:
      create: true
      name: homepage