apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/homepage
      version: "1.3.2"
      sourceRef:
        kind: GitRepository
        name: monsterrr
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: latest
      pullPolicy: IfNotPresent

    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

    initContainers:
      - name: init-chown-data
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /app/config && chmod -R 755 /app/config"]
        volumeMounts:
          - name: config
            mountPath: /app/config

    volumes:
      - name: config
        persistentVolumeClaim:
          claimName: homepage-config

    volumeMounts:
      - name: config
        mountPath: /app/config

    env:
      - name: HOMEPAGE_ALLOWED_HOSTS
        value: "homepage.internal"

    service:
      port: 3000
      targetPort: 3000

    ingress:
      enabled: true
      ingressClassName: public
      hosts:
        - host: homepage.internal
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: homepage-tls
          hosts:
            - homepage.internal 
