apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/homepage
      version: "1.3.2"
      sourceRef:
        kind: GitRepository
        name: monsterrr
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: latest
      pullPolicy: IfNotPresent

    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

    persistence:
      config:
        enabled: true
        existingClaim: homepage-config
        mountPath: /app/config

    env:
      - name: HOMEPAGE_ALLOWED_HOSTS
        value: "homepage.local"

    service:
      main:
        ports:
          http:
            enabled: true
            port: 3000
            targetPort: 3000

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - homepage.local
        paths:
          - path: /
            pathType: Prefix
        tls:
          - secretName: homepage-tls
            hosts:
              - homepage.local 