apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: monsterrr
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/M0NsTeRRR/helm-charts
  ref:
    branch: main 