apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helm-repository.yaml
  - helmrelease.yaml
  - pvc.yaml
  - configmap.yaml
  - homepage-traefik-ingress.yaml 