apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-server
  namespace: minecraft
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft
      version: "4.15.0"
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: minecraft
  values:
    image:
      tag: latest
    minecraftServer:
      eula: true
      type: PAPER
      version: "1.20.1"
      rcon:
        enabled: true
        password: "minecraft-rcon-password"
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Minecraft Server (Java + Bedrock)
        gethomepage.dev/group: Gaming
        gethomepage.dev/name: "Minecraft Server"
        gethomepage.dev/icon: "https://www.minecraft.net/content/dam/games/minecraft/key-art/MC_Java_KeyArt_600x300.jpg"
    extraPorts:
      - name: bedrock
        containerPort: 19132
        protocol: UDP
        servicePort: 19132
    persistence:
      enabled: true
      storageClass: "nfs-client"
      accessMode: ReadWriteOnce
      size: 10Gi
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
      limits:
        memory: "4Gi"
        cpu: "2000m"
    env:
      ENABLE_RCON: "true"
      USE_AIKAR_FLAGS: "true"
      MEMORY: "2G"
      ENABLE_GEYSER: "true"
      ENABLE_FLOODGATE: "true"
    # Enable plugin mounting
    extraVolumes:
      - name: plugins
        emptyDir: {}
    extraVolumeMounts:
      - name: plugins
        mountPath: /data/plugins
    # Init containers to download plugins
    initContainers:
      - name: download-geyser
        image: curlimages/curl:latest
        command: ["sh", "-c"]
        args:
          - |
            echo "Downloading GeyserMC plugin..."
            curl -L -o /plugins/geyser-spigot.jar "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot"
            echo "GeyserMC download complete"
        volumeMounts:
          - name: plugins
            mountPath: /plugins
      - name: download-floodgate
        image: curlimages/curl:latest
        command: ["sh", "-c"]
        args:
          - |
            echo "Downloading Floodgate plugin..."
            curl -L -o /plugins/floodgate-spigot.jar "https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot"
            echo "Floodgate download complete"
        volumeMounts:
          - name: plugins
            mountPath: /plugins
    # Server properties for GeyserMC
    serverProperties:
      server-port: 25565
      enable-rcon: true
      rcon.port: 25575
      rcon.password: minecraft-rcon-password
      online-mode: false
      allow-nether: true
      level-name: world
      enable-command-block: true
      gamemode: survival
      hardcore: false
      max-players: 20
      pvp: true
      difficulty: easy
      enable-query: true
      query.port: 25565
      enable-status: true
      motd: "Flux Home Lab Minecraft Server"

