apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft
spec:
  interval: 10m
  chart:
    spec:
      chart: minecraft
      version: 4.12.0
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: minecraft
  values:
    EULA: "TRUE"
    TYPE: "PAPER"
    VERSION: "1.20.1"
    MEMORY: "4G"
    ENABLE_RCON: true
    RCON_PASSWORD: "changeme"
    SERVER_PORT: 25565
    BEDROCK_PORT: 19132
    PLUGINS: "https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/lastSuccessfulBuild/artifact/bootstrap/spigot/target/Geyser-Spigot.jar,https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/master/lastSuccessfulBuild/artifact/spigot/target/floodgate-spigot.jar"
    extraPorts:
      - name: bedrock
        containerPort: 19132
        protocol: UDP
    persistence:
      enabled: true
      existingClaim: minecraft-data
