apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helm-repository.yaml
  - helmrelease.yaml
  - geyser-config.yaml
  - floodgate-config.yaml
  - plugins-list.yaml
  - minecraft-traefik-ingress.yaml
