apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-startup-script
  namespace: minecraft
data:
  startup.sh: |
    #!/bin/bash
    set -e
    
    echo "Starting Minecraft server with plugin auto-download..."
    
    # Create plugins directory if it doesn't exist
    mkdir -p /data/plugins
    
    # Download GeyserMC plugin if not present
    if [ ! -f "/data/plugins/geyser-spigot.jar" ]; then
      echo "Downloading GeyserMC plugin..."
      curl -L -o /data/plugins/geyser-spigot.jar "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot"
      echo "GeyserMC plugin downloaded"
    else
      echo "GeyserMC plugin already exists"
    fi
    
    # Download Floodgate plugin if not present
    if [ ! -f "/data/plugins/floodgate-spigot.jar" ]; then
      echo "Downloading Floodgate plugin..."
      curl -L -o /data/plugins/floodgate-spigot.jar "https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot"
      echo "Floodgate plugin downloaded"
    else
      echo "Floodgate plugin already exists"
    fi
    
    echo "Plugins ready, starting Minecraft server..."
    
    # Execute the original Minecraft server startup
    exec /start
