---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teslamate-postgres-nfs
  namespace: teslamate
spec:
  interval: 1h
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: teslamate
      chart: postgresql
      version: 11.1.26
  releaseName: teslamate-postgres-nfs
  values:
    settings:
      superuserPasswordSecret:
        name: "teslamate-postgres"
        key: "postgres_user_pass"
      databases:
        - name: teslamate
          user: teslamate
          passwordSecret:
            name: "teslamate-postgres"
            key: "teslamate_user_pass"
    
    storage:
      requestedSize: "8Gi"
      className: "nfs-client"
      accessModes:
        - ReadWriteMany
      annotations:
        nfs.io/createUID: "999"
        nfs.io/createGID: "999"
        nfs.io/createMode: "0755"
    
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    
    service:
      type: ClusterIP
      port: 5432
    
    # Enable metrics for monitoring
    metrics:
      enabled: false
    
    # Security context similar to Bitnami setup
    securityContext:
      runAsUser: 999
      runAsGroup: 999
      fsGroup: 999