---
apiVersion: v1
kind: Service
metadata:
  name: teslamate-postgres
  namespace: teslamate
spec:
  selector:
    app: teslamate-postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP