---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: teslamate-postgres
  namespace: teslamate
spec:
  serviceName: teslamate-postgres
  replicas: 1
  selector:
    matchLabels:
      app: teslamate-postgres
  template:
    metadata:
      labels:
        app: teslamate-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: teslamate
        - name: POSTGRES_USER
          value: teslamate
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: teslamate-postgres
              key: teslamate_user_pass
        - name: POSTGRES_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: teslamate-postgres
              key: postgres_user_pass
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - teslamate
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - teslamate
          initialDelaySeconds: 5
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
      annotations:
        nfs.io/createUID: "999"
        nfs.io/createGID: "999"
        nfs.io/createMode: "0755"
    spec:
      accessModes: ["ReadWriteMany"]
      storageClassName: "nfs-client"
      resources:
        requests:
          storage: 8Gi