---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: bitnami-postgresql
  namespace: teslamate
spec:
  interval: 24h
  chart: postgresql
  version: 16.7.27
  sourceRef:
    kind: HelmRepository
    name: bitnami
