---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder
  namespace: coder
spec:
  interval: 30m
  chart:
    spec:
      chart: coder
      sourceRef:
        kind: HelmRepository
        name: coder
        namespace: coder
      interval: 12h
  values:
    coder: 
      # Expose via Traefik using the repo's internal CA
      ingress:
        enable: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
          cert-manager.io/cluster-issuer: internal-ca
        host: coder.internal
        tls:
          enable: true
          hostSecretName: coder-tls

      service:
        type: ClusterIP

      env:
        - name: CODER_ACCESS_URL
          value: https://coder.internal
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: coder-postgres
              key: url
 