apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alloy/
  - mosquitto/
  - frigate/
  - homeassistant/
  - homepage/
  - loki/
  - loki-stack/
  - metallb/
  - prometheus/
  - coder/
  - tandoor/
  - teslamate/
  - traefik/
  - unifi/
  - uptime-kuma/