---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: uptime-kuma
      version: 4.7.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: monitoring
  releaseName: uptime-kuma
  values:
    persistence:
      enabled: true
      storageClass: nfs-client
      accessModes:
        - ReadWriteMany
      size: 8Gi
      annotations:
        nfs.io/createUID: "1001"
        nfs.io/createGID: "1001"
        nfs.io/createMode: "0755"
    service:
      type: ClusterIP
      port: 3001
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
