apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: "2.31.0"
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
  values:
    image:
      repository: pihole/pihole
      tag: latest
      pullPolicy: IfNotPresent

    persistence:
      enabled: true
      size: 10Gi
      storageClass: "nfs-client"

    env:
      TZ: "America/Chicago"
      WEBPASSWORD: "changeme"  # Change this to a secure password
      VIRTUAL_HOST: "pihole.local"
      PROXY_LOCATION: "pihole"
      ServerIP: "192.168.86.31"  # Your node IP
      DNS1: "8.8.8.8"
      DNS2: "1.1.1.1"

    service:
      dns:
        enabled: true
        port: 5353
        type: ClusterIP
      http:
        enabled: true
        port: 81
        type: ClusterIP

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - pihole.local
      paths:
        - path: /
          pathType: Prefix
      tls:
        - secretName: pihole-tls
          hosts:
            - pihole.local

    hostNetwork: false
    dnsPolicy: ClusterFirst 