---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: piped
  namespace: piped
spec:
  interval: 30m
  chart:
    spec:
      chart: piped
      sourceRef:
        kind: HelmRepository
        name: piped
        namespace: piped
      interval: 12h
  values:
    frontend:
      enabled: true
      containerSecurityContext:
        capabilities:
          add:
            - NET_BIND_SERVICE
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
          cert-manager.io/cluster-issuer: internal-ca
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Piped - Self-hosted YouTube frontend
          gethomepage.dev/group: Media
          gethomepage.dev/name: "Piped"
          gethomepage.dev/icon: "https://piped.video/favicon.ico"
        hosts:
          - host: piped.internal
            paths:
              - /
        tls:
          - hosts:
              - piped.internal
            secretName: piped-tls
      env:
        FRONTEND_URL: https://piped.internal

    backend:
      enabled: true
      config:
        FRONTEND_URL: https://piped.internal
        DISABLE_REGISTRATION: "true"
        SPONSORBLOCK_ENABLED: "true"
        database:
          connection_url: jdbc:postgresql://piped-postgresql-rw:5432/piped
          driver_class: org.postgresql.Driver
          dialect: org.hibernate.dialect.PostgreSQLDialect
          secret:
            name: piped-postgres

    proxy:
      enabled: true

    postgresql:
      enabled: true
      auth:
        database: piped
        username: piped
        existingSecret: "piped-postgres"
        secretKeys:
          adminPasswordKey: "postgres-password"
          userPasswordKey: "password"
      primary:
        persistence:
          enabled: true
          storageClass: "nfs-client"
          size: 8Gi

    redis:
      enabled: true

