apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: piped-postgresql
  namespace: piped
spec:
  instances: 1
  postgresql:
    version: 15
  storage:
    size: 8Gi
    storageClass: nfs-client
  bootstrap:
    initdb:
      database: piped
      owner: piped
      secret:
        name: piped-postgres
  # Note: `users` managed via bootstrap.initdb.secret; operator will use the
  # secret named above to create the initial user and database.
