apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: piped-postgresql
  namespace: piped
spec:
  instances: 1
  postgresql:
    version: 15
  storage:
    size: 8Gi
    storageClassName: nfs-client
  bootstrap:
    initdb:
      database: piped
      username: piped
  users:
    - name: piped
      password:
        secretName: piped-postgres
        secretKey: password
  # Note: `superuser` removed — CloudNativePG Cluster CRD may not accept this field.
  # If you need to set the superuser password explicitly, add it according to
  # the installed CRD schema (inspect with
  # `kubectl get crd clusters.postgresql.cnpg.io -o yaml`).
