---
# SealedSecret for Piped PostgreSQL credentials
# To regenerate the encrypted values (if the controller service is not directly accessible):
# 1. Extract the public cert: kubectl get secret -n flux-system -l sealedsecrets.bitnami.com/sealed-secrets-key=active -o jsonpath='{.items[0].data.tls\.crt}' | base64 -d > /tmp/sealed-secrets-public-cert.pem
# 2. Create a temporary Secret: kubectl create secret generic piped-postgres --from-literal=postgres-password='YOUR_PASSWORD' --from-literal=password='YOUR_PASSWORD' --dry-run=client -o yaml -n piped > /tmp/piped-postgres-secret.yaml
# 3. Seal it using the cert: kubeseal --cert=/tmp/sealed-secrets-public-cert.pem -o yaml < /tmp/piped-postgres-secret.yaml > /tmp/piped-postgres-sealed.yaml
# 4. Copy the encryptedData values from /tmp/piped-postgres-sealed.yaml to this file
# 5. Clean up: rm /tmp/piped-postgres-secret.yaml /tmp/sealed-secrets-public-cert.pem
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: piped-postgres
  namespace: piped
spec:
  encryptedData:
    postgres-password: AgB8v6gcD5xj553O1hf76YdwV8lbeZXBNR52Rw6jQQrEhKQhVVpGGPR9/FtbJjw19CdRYPWjdpynStGwnqYu9NunxqCBNlpBZ5jOt86BYZnf9c8Ai6IDZ2ZJ5sQA9xGqV/ERHQbUuiwXL7BdZDelgOuWAjPAOkhIihgvIj2siO0QTno67yG8YbePPl3SZa2d03i856FczFlFbjlGtGjIAwM41N0VBjZlpDfQ99W5P9sjC9obSzJ3ELMYU4B956wR5aK70zqe8/IMWNWFVm8E+kgrnFCyasdtOKaKLdr3pQOd7rVrmUJOxhnMh3qpB4D6qMo9byu7j06EkcDKu6m2b4Vgg6uHs5HeNYGqEl40aEDCsgBjxxaFRflln6vVlua0bhsDO9CunWIKFO7XNvEVPqNAng/4Nu4qSIyVp5HLDkwbQrbGJwB8ldFjATP45gNicvXno7FtEPntdNrZIImZd2f7nsPzdvEOO1FPHs1MkidbMZ0kCPg0m58o2X32UF4OM3xmg4bWFNavavK3ZEjTcy4vGehGI3+nvvAEV13gORLLRQXYGUrusROU8rfpn+3mYFpT1LT+MHEAksb4v3u5GZQpLU7E2RS//coMoeFzhkolWvQS70G6y+6WaXgLveN92PTNc0RTp+pSVxTgH+/42p3S99X3FUNo+nuvkmzn1mAizgaevasO1Y3E35XaLmwesPhLq4fqqVMjRFagMr5k1i/8yJknmQ==
    password: AgCcUTXYywJyVmlpuhMGI62cYOBbACtu4k7JAUu5dL8LwXZ3TvAUrTBQ0exOsr1R5YDtBKjCdPrgAq5PK0oyoJLTsyioke3KRsu1AXSlYKpED/drosca0xg7VlYElFYndxjw+3A8psMWe3DetH9QpjVGDWpGVDPK+fLeURfXOYl9m0z3n508bBipM6+kNo6JNRmKIEorJJU5vG7HrkJoTcxlmRj6UAjgGn3YIxVz/c7LrjkGrxKq9yToJNw2DtaarvuB6jNo0apStW3DUCLJdu39V0Bax+mp0PO7A8KbpCH0Vfv6HaWSoQhtRAzy4E8osTdzdePUsvNi/30tJFJ9AzIyXB7nV+3vfcWxc+ektkT8mpnk3fsoaePDcFLkgTGvo8HRim7jmDEqFSPEmUbfAuGePLR5p3GCJyFGPcIBJpswnzXcQCt2ROHnCdd2Ah+18q8wstSCBXBGk5E7pA71Td6r04lESYVQ9zi5wjowOqUIa+Yna2iWwYOwdH6tXrw67rVo5TQM9keoa3BwJKStid/bqHLYG6jDfKGxO6Zzvt3d+XZJk2wmUGzoIVLYNOmwGcBa2Au/ywvj0qP7SsGM6+1nXzJKDeAVzQnxtSLSTUFZKOF/G5dGa7SYddJiDJTj5hcgJN+Tr3wmYVsB0xZNabmB8j4Fx6fsTVFqA3i39BGTRaJftVtocQl60uS2/zDDbyaymcDxBkTX7+bICqmBFYJUkmEvGw==
  template:
    metadata:
      creationTimestamp: null
      name: piped-postgres
      namespace: piped
    type: Opaque

