apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: loki-stack
      version: "2.9.10"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  values:
    # Loki configuration
    loki:
      auth_enabled: false
      commonConfig:
        path_prefix: /var/loki
        storage:
          filesystem:
            chunks_directory: /var/loki/chunks
            rules_directory: /var/loki/rules
        replication_factor: 1
        ring:
          kvstore:
            store: inmemory
      schema_config:
        configs:
          - from: 2020-10-24
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h
      storage_config:
        boltdb_shipper:
          active_index_directory: /var/loki/boltdb-shipper-active
          cache_location: /var/loki/boltdb-shipper-cache
          cache_ttl: 24h
          shared_store: filesystem
        filesystem:
          directory: /var/loki/chunks
      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
      chunk_store_config:
        max_look_back_period: 0s
      table_manager:
        retention_deletes_enabled: false
        retention_period: 0s
      persistence:
        enabled: true
        storageClass: "nfs-client"
        accessModes:
          - ReadWriteMany
        size: 10Gi
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi

    # Grafana configuration
    grafana:
      enabled: true
      adminPassword: "admin"  # You should change this or use a secret
      persistence:
        enabled: true
        storageClass: "nfs-client"
        accessModes:
          - ReadWriteOnce
        size: 5Gi
      ingress:
        enabled: true
        ingressClassName: "public"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Grafana Dashboard
          gethomepage.dev/group: Monitoring
          gethomepage.dev/name: "Grafana"
          gethomepage.dev/icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Grafana_logo.svg/1024px-Grafana_logo.svg.png"
        hosts:
          - host: grafana.internal
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.internal
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi

    # Promtail configuration for log collection
    promtail:
      enabled: true
      config:
        server:
          http_listen_port: 9080
          grpc_listen_port: 0
        positions:
          filename: /tmp/positions.yaml
        clients:
          - url: http://loki:3100/loki/api/v1/push
        scrape_configs:
          - job_name: kubernetes-pods-name
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels:
                  - __meta_kubernetes_pod_label_app
                regex: .+
                action: keep
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                target_label: __service__
              - source_labels:
                  - __meta_kubernetes_pod_name
                target_label: __service__
              - source_labels:
                  - __meta_kubernetes_pod_label_app
                target_label: app
              - source_labels:
                  - __meta_kubernetes_namespace_name
                target_label: namespace
              - source_labels:
                  - __meta_kubernetes_pod_name
                target_label: pod
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                target_label: container
              - source_labels:
                  - __meta_kubernetes_pod_container_id
                target_label: __path__
                regex: (.+)
                replacement: /var/log/pods/*$1/*.log
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - source_labels:
                  - __meta_kubernetes_namespace_name
                action: replace
                target_label: namespace
              - source_labels:
                  - __meta_kubernetes_pod_name
                action: replace
                target_label: pod
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                action: replace
                target_label: container
              - regex: /var/log/pods/(.+)/(.+)/.+
                replacement: /var/log/pods/$1/$2
                target_label: __path__
          - job_name: kubernetes-pods-app
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels:
                  - __meta_kubernetes_pod_label_app
                regex: .+
                action: keep
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                target_label: __service__
              - source_labels:
                  - __meta_kubernetes_pod_label_app
                target_label: app
              - source_labels:
                  - __meta_kubernetes_namespace_name
                target_label: namespace
              - source_labels:
                  - __meta_kubernetes_pod_name
                target_label: pod
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                target_label: container
              - source_labels:
                  - __meta_kubernetes_pod_container_id
                target_label: __path__
                regex: (.+)
                replacement: /var/log/pods/*$1/*.log
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - source_labels:
                  - __meta_kubernetes_namespace_name
                action: replace
                target_label: namespace
              - source_labels:
                  - __meta_kubernetes_pod_name
                action: replace
                target_label: pod
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                action: replace
                target_label: container
              - regex: /var/log/pods/(.+)/(.+)/.+
                replacement: /var/log/pods/$1/$2
                target_label: __path__
          - job_name: kubernetes-pods-direct-controllers
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels:
                  - __meta_kubernetes_pod_label_app
                regex: .+
                action: keep
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                regex: .+
                action: keep
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                target_label: __service__
              - source_labels:
                  - __meta_kubernetes_pod_label_app
                target_label: app
              - source_labels:
                  - __meta_kubernetes_namespace_name
                target_label: namespace
              - source_labels:
                  - __meta_kubernetes_pod_name
                target_label: pod
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                target_label: container
              - source_labels:
                  - __meta_kubernetes_pod_container_id
                target_label: __path__
                regex: (.+)
                replacement: /var/log/pods/*$1/*.log
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - source_labels:
                  - __meta_kubernetes_namespace_name
                action: replace
                target_label: namespace
              - source_labels:
                  - __meta_kubernetes_pod_name
                action: replace
                target_label: pod
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                action: replace
                target_label: container
              - regex: /var/log/pods/(.+)/(.+)/.+
                replacement: /var/log/pods/$1/$2
                target_label: __path__
          - job_name: kubernetes-pods-indirect-controller
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels:
                  - __meta_kubernetes_pod_label_app
                regex: .+
                action: keep
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                regex: .+
                action: keep
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                target_label: __service__
              - source_labels:
                  - __meta_kubernetes_pod_label_app
                target_label: app
              - source_labels:
                  - __meta_kubernetes_namespace_name
                target_label: namespace
              - source_labels:
                  - __meta_kubernetes_pod_name
                target_label: pod
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                target_label: container
              - source_labels:
                  - __meta_kubernetes_pod_container_id
                target_label: __path__
                regex: (.+)
                replacement: /var/log/pods/*$1/*.log
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - source_labels:
                  - __meta_kubernetes_namespace_name
                action: replace
                target_label: namespace
              - source_labels:
                  - __meta_kubernetes_pod_name
                action: replace
                target_label: pod
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                action: replace
                target_label: container
              - regex: /var/log/pods/(.+)/(.+)/.+
                replacement: /var/log/pods/$1/$2
                target_label: __path__
          - job_name: kubernetes-pods-static
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels:
                  - __meta_kubernetes_pod_label_app
                regex: .+
                action: keep
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                target_label: __service__
              - source_labels:
                  - __meta_kubernetes_pod_label_app
                target_label: app
              - source_labels:
                  - __meta_kubernetes_namespace_name
                target_label: namespace
              - source_labels:
                  - __meta_kubernetes_pod_name
                target_label: pod
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                target_label: container
              - source_labels:
                  - __meta_kubernetes_pod_container_id
                target_label: __path__
                regex: (.+)
                replacement: /var/log/pods/*$1/*.log
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - source_labels:
                  - __meta_kubernetes_namespace_name
                action: replace
                target_label: namespace
              - source_labels:
                  - __meta_kubernetes_pod_name
                action: replace
                target_label: pod
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                action: replace
                target_label: container
              - regex: /var/log/pods/(.+)/(.+)/.+
                replacement: /var/log/pods/$1/$2
                target_label: __path__
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi

    # Disable Prometheus since we're focusing on logs
    prometheus:
      enabled: false 