apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: loki-stack
      version: "2.9.10"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  values:
    # Loki configuration
    loki:
      auth_enabled: false
      commonConfig:
        path_prefix: /var/loki
        storage:
          filesystem:
            chunks_directory: /var/loki/chunks
            rules_directory: /var/loki/rules
        replication_factor: 1
        ring:
          kvstore:
            store: inmemory
        querier:
          extra_query_delay: 500ms
        frontend:
          scheduler_worker_concurrency: 15
        query_scheduler:
          max_outstanding_requests_per_tenant: 1000
      schema_config:
        configs:
          - from: 2020-10-24
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h
      storage_config:
        boltdb_shipper:
          active_index_directory: /var/loki/boltdb-shipper-active
          cache_location: /var/loki/boltdb-shipper-cache
          cache_ttl: 24h
          shared_store: filesystem
        filesystem:
          directory: /var/loki/chunks
      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
        max_query_lookback: 168h  # 7 days
        retention_period: 168h    # 7 days for detailed logs
        retention_stream:
        - selector: '{namespace="kube-system"}'
          priority: 1
          period: 336h  # 14 days for system logs
        - selector: '{namespace="monitoring"}'
          priority: 1
          period: 336h  # 14 days for monitoring logs
        - selector: '{app="teslamate"}'
          priority: 2
          period: 720h  # 30 days for TeslaMate logs (higher priority)
      chunk_store_config:
        max_look_back_period: 168h  # Match retention period
      compactor:
        working_directory: /var/loki/compactor
        shared_store: filesystem
        retention_enabled: true
        delete_request_store: filesystem
        compaction_interval: 10m
        retention_delete_worker_count: 150
        retention_delete_delay: 2h
      persistence:
        enabled: true
        storageClass: "nfs-client"
        accessModes:
          - ReadWriteMany
        size: 10Gi
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi

    # Grafana configuration
    grafana:
      enabled: true
      adminPassword: "admin"  # You should change this or use a secret
      persistence:
        enabled: true
        storageClass: "nfs-client"
        accessModes:
          - ReadWriteOnce
        size: 5Gi
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Grafana Dashboard
          gethomepage.dev/group: Monitoring
          gethomepage.dev/name: "Grafana"
          gethomepage.dev/icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Grafana_logo.svg/1024px-Grafana_logo.svg.png"
        hosts:
          - grafana.internal
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi

    # Promtail configuration for log collection
    promtail:
      enabled: true
      config:
        server:
          log_level: info
          http_listen_port: 3101
        clients:
          - url: http://loki-stack:3100/loki/api/v1/push
        positions:
          filename: /run/promtail/positions.yaml
        scrape_configs:
          - job_name: kubernetes-pods
            read_from_head: false
            pipeline_stages:
              - cri: {}
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels:
                  - __meta_kubernetes_pod_controller_name
                regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
                action: replace
                target_label: __tmp_controller_name
              - source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_name
                  - __meta_kubernetes_pod_label_app
                  - __tmp_controller_name
                  - __meta_kubernetes_pod_name
                regex: ^;*([^;]+)(;.*)?$
                action: replace
                target_label: app
              - source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_instance
                  - __meta_kubernetes_pod_label_release
                regex: ^;*([^;]+)(;.*)?$
                action: replace
                target_label: instance
              - source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_component
                  - __meta_kubernetes_pod_label_component
                regex: ^;*([^;]+)(;.*)?$
                action: replace
                target_label: component
              - action: replace
                source_labels:
                  - __meta_kubernetes_pod_node_name
                target_label: node_name
              - action: replace
                source_labels:
                  - __meta_kubernetes_namespace
                target_label: namespace
              - action: replace
                replacement: $1
                separator: /
                source_labels:
                  - namespace
                  - app
                target_label: job
              - action: replace
                source_labels:
                  - __meta_kubernetes_pod_name
                target_label: pod
              - action: replace
                source_labels:
                  - __meta_kubernetes_pod_container_name
                target_label: container
              - action: replace
                replacement: /var/log/pods/*$1/*.log
                separator: /
                source_labels:
                  - __meta_kubernetes_pod_uid
                  - __meta_kubernetes_pod_container_name
                target_label: __path__
              - action: replace
                regex: true/(.*)
                replacement: /var/log/pods/*$1/*.log
                separator: /
                source_labels:
                  - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
                  - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
                  - __meta_kubernetes_pod_container_name
                target_label: __path__
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi

    # Disable Prometheus since we're focusing on logs
    prometheus:
      enabled: false 