---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tandoor
  namespace: tandoor
spec:
  chart:
    spec:
      chart: tandoor
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gabe565
  interval: 1h
  releaseName: tandoor
  # Patch to add emptyDir volume at /run for Gunicorn socket
  # Fix for Tandoor 2.3.3+ Gunicorn socket permission issue
  # See: https://github.com/TandoorRecipes/recipes/issues/4209
  patches:
    - patch: |
        - op: add
          path: /spec/template/spec/volumes/-
          value:
            name: run-socket
            emptyDir: {}
        - op: add
          path: /spec/template/spec/containers/0/volumeMounts/-
          value:
            name: run-socket
            mountPath: /run
      target:
        kind: Deployment
        name: tandoor
  values:
    #
    # IMPORTANT NOTE
    #
    # This chart inherits from our common library chart. You can check the default values/options here:
    # https://github.com/bjw-s/helm-charts/blob/a081de5/charts/library/common/values.yaml
    #

    image:
      # -- image repository
      repository: ghcr.io/tandoorrecipes/recipes
      # -- image tag
      tag: 2.3.3
      # -- image pull policy
      pullPolicy: IfNotPresent
      # -- image tag

    # -- environment variables. [[ref]](https://github.com/TandoorRecipes/recipes/blob/master/.env.template).
    # @default -- See [values.yaml](./values.yaml)
    env:
      # -- default timezone
      TIMEZONE: UTC
      SOCIAL_PROVIDERS: 
      # SECRET_KEY: changeme

    service:
      # -- Configures service settings for the chart.
      # @default -- See [values.yaml](./values.yaml)
      main:
        ports:
          http:
            port: 8080
          static:
            port: 80

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See [values.yaml](./values.yaml)
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Tandoor Recipes
          gethomepage.dev/group: Lifestyle
          gethomepage.dev/name: "Tandoor Recipes"
          gethomepage.dev/icon: "https://tandoor.dev/static/assets/brand_logo.png"
        hosts:
          - host: recipes.internal
            paths:
              - path: /
              - path: /static
                service:
                  port: 80
              - path: /media
                service:
                  port: 80

    # -- Configure persistence settings for the chart under this key.
    # @default -- See [values.yaml](./values.yaml)
    persistence:
      config:
        enabled: true
        retain: true
        storageClass: "nfs-client"
        accessMode: ReadWriteOnce
        size: 1Gi
      media:
        enabled: true
        mountPath: /opt/recipes/mediafiles
        retain: true
        storageClass: "nfs-client"
        accessMode: ReadWriteOnce
        size: 1Gi
      static:
        enabled: true
        type: emptyDir
        mountPath: /opt/recipes/staticfiles
      django-js-reverse:
        enabled: true
        type: emptyDir
        mountPath: /opt/recipes/cookbook/static/django_js_reverse
      # Fix for Tandoor 2.3.3+ Gunicorn socket permission issue
      # See: https://github.com/TandoorRecipes/recipes/issues/4209
      run:
        enabled: true
        type: emptyDir
        mountPath: /run

    # -- Enable and configure postgresql database subchart under this key. [[ref]](https://github.com/bitnami/charts/tree/master/bitnami/mariadb)
    # @default -- See [values.yaml](./values.yaml)
    postgresql:
      enabled: true
      auth:
        database: tandoor
        postgresPassword: changeme
      primary:
        persistence:
          enabled: true
          storageClass: "nfs-client"
          size: 8Gi

    podSecurityContext:
      # -- Run as `nobody` user
      runAsUser: 65534
      # -- Run as `nobody` group
      runAsGroup: 65534
      # -- Volume binds will be granted to `nobody` group
      fsGroup: 65534