apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - source-helmrepo-gabe565.yaml
  - helmrelease.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - tandoor-postgres-secret.yaml
  - tandoor-postgres-sealedsecret.yaml 