---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tandoor-postgres
  namespace: tandoor
spec:
  serviceName: tandoor-postgres
  replicas: 1
  selector:
    matchLabels:
      app: tandoor-postgres
  template:
    metadata:
      labels:
        app: tandoor-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: tandoor
        - name: POSTGRES_USER
          value: tandoor
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tandoor-postgres-secret
              key: password
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - tandoor
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - tandoor
          initialDelaySeconds: 5
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
      annotations:
        nfs.io/createUID: "999"
        nfs.io/createGID: "999"
        nfs.io/createMode: "0755"
    spec:
      accessModes: ["ReadWriteMany"]
      storageClassName: "nfs-client"
      resources:
        requests:
          storage: 8Gi