---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tandoor-postgres
  namespace: tandoor
spec:
  interval: 1h
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: tandoor
      chart: postgresql
      version: 11.1.26
  releaseName: tandoor-postgres
  values:
    settings:
      superuserPasswordSecret:
        name: "tandoor-postgres-secret"
        key: "postgres_password"
      databases:
        - name: tandoor
          user: tandoor
          passwordSecret:
            name: "tandoor-postgres-secret"
            key: "tandoor_password"
    
    storage:
      requestedSize: "8Gi"
      className: "nfs-client"
      accessModes:
        - ReadWriteMany
      annotations:
        nfs.io/createUID: "999"
        nfs.io/createGID: "999"
        nfs.io/createMode: "0755"
    
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    
    service:
      type: ClusterIP
      port: 5432
    
    # Security context
    securityContext:
      runAsUser: 999
      runAsGroup: 999
      fsGroup: 999