---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tandoor-postgres-secret
  namespace: tandoor
spec:
  encryptedData:
    postgres_password: AgBL8x+9g1h2N3D5k7M9P2qWe8R4T6Y3uIo0VbNmAsQc1ZxCvBnMaLkJhGfDsSA
    tandoor_password: AgAn2x5C8e1Q4w9R7t6Y2uPvB5nM3K8L0jHsGfDaSkQp9ZrTvNmXlCoIhBdEaGb
  template:
    metadata:
      creationTimestamp: null
      name: tandoor-postgres-secret
      namespace: tandoor
    type: Opaque