---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tandoor-postgres-secret
  namespace: tandoor
spec:
  encryptedData:
    password: AgBtYnVlNFh2bXBlc1F6K1Y4RGMvQXNRSk1WblFRVmZUdjhiNXVKK3dOTHE1UGQva0xycEd2REUzOFNaMEE4
  template:
    metadata:
      creationTimestamp: null
      name: tandoor-postgres-secret
      namespace: tandoor
    type: Opaque