apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eero-exporter
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: eero-exporter
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s 