---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: bitnami-postgresql
  namespace: teslamate
spec:
  chart: postgresql
  version: 16.2.1
  sourceRef:
    kind: OCIRepository
    name: bitnami-oci
    namespace: teslamate

