---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teslamate-core
  namespace: teslamate
spec:
  chart:
    spec:
      chart: teslamate
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  interval: 1h
  releaseName: teslamate-core
  values:
    image:
      repository: teslamate/teslamate
      tag: "1.33"
      pullPolicy: IfNotPresent
    service:
      main:
        ports:
          http:
            port: 4000
    nodeSelector:
      disktype: ssd
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "public"
        hosts:
          - host: teslamate.internal
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 4000
    env:
      - name: TZ 
        value: UTC
      - name: DATABASE_HOST
        value: teslamate-postgres-nfs-postgresql
      - name: DATABASE_PORT
        value: 5432
      - name: DATABASE_USER
        value: postgres
      - name: DATABASE_PASS
        valueFrom:
          secretKeyRef:
            name: teslamate-postgres
            key: postgres_user_pass
      - name: DATABASE_NAME
        value: teslamate
      - name: DISABLE_MQTT
        value: "true"
      - name: ENCRYPTION_KEY
        valueFrom:
          secretKeyRef:
            name: teslamate-postgres
            key: encryption_key
      - name: WAFFLES
        value: "true"
    persistence:
      import:
        enabled: false
        mountPath: /opt/app/import
