---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  chart:
    spec:
      chart: home-assistant
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pajikos
      # appVersion: "2025.7.1"

  interval: 1h
  releaseName: homeassistant
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: "2025.9"
      pullPolicy: IfNotPresent

    # Environment variables
    env:
      - name: TZ
        value: UTC

    # Enable hostNetwork for device discovery
    hostNetwork: true

    # Ingress configuration
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Home Assistant
        gethomepage.dev/group: Automation
        gethomepage.dev/name: "Home Assistant"
        gethomepage.dev/icon: "https://raw.githubusercontent.com/home-assistant/assets/master/logo/logo.png"
      hosts:
        - host: homeassistant.internal
          paths:
            - path: /
              pathType: Prefix

    # Persistence configuration
    persistence:
      enabled: true
      storageClass: "nfs-client"
      size: 5Gi

    # Home Assistant configuration
    configuration:
      enabled: true
      trusted_proxies:
        - 192.168.86.0/24
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 127.0.0.0/8
      templateConfig: |-
        # Loads default set of integrations. Do not remove.
        default_config:

        # Load frontend
        frontend:

        # Load integrations
        config:

        # Reverse proxy configuration
        http:
          use_x_forwarded_for: true
          trusted_proxies:
            {{- range .Values.configuration.trusted_proxies }}
            - {{ . | quote }}
            {{- end }}

    # Resource limits
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 1Gi 