---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  chart:
    spec:
      chart: home-assistant
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      # appVersion: "2025.1.0"

  interval: 1h
  releaseName: homeassistant
  values:
    image:
      # -- image repository
      repository: homeassistant/home-assistant
      # -- image tag
      # @default -- chart.appVersion
      tag: "2025.7"
      # -- image pull policy
      pullPolicy: IfNotPresent

    # -- environment variables. See [image docs](https://www.home-assistant.io/docs/installation/docker/) for more details.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: UTC
      # -- Specify the user ID the application will run as
      PUID: "1000"
      # -- Specify the group ID the application will run as
      PGID: "1000"
      # -- Trust reverse proxy headers
      HTTP_PROXY: "true"
      # -- Trusted proxies (your node IPs)
      TRUSTED_PROXIES: "192.168.86.0/24"
      # -- Use X-Forwarded-For headers
      USE_X_FORWARDED_FOR: "true"

    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 8123

    # -- Enable hostNetwork - needed for device discovery
    hostNetwork: true

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Home Assistant
          gethomepage.dev/group: Automation
          gethomepage.dev/name: "Home Assistant"
          gethomepage.dev/icon: "https://raw.githubusercontent.com/home-assistant/assets/master/logo/logo.png"
        hosts:
          - host: homeassistant.internal
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 8123

    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      config:
        enabled: true
        mountPath: /config
        storageClass: "nfs-client"

    # -- Configure security settings for the chart under this key.
    # @default -- See values.yaml
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

    # -- Configure resource requests and limits
    # @default -- See values.yaml
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 1Gi 