---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: pajikos
  namespace: homeassistant
spec:
  interval: 24h
  url: http://pajikos.github.io/home-assistant-helm-chart/ 