---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: syncify
  namespace: syncify
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: syncify
  releaseName: syncify
  values:
    controllers:
      main:
        strategy: Recreate
        containers:
          app:
            image:
              repository: docker.io/cjchand/syncify
              tag: latest
            env:
              PUID: "1000"
              PGID: "1000"
              thread_limit: "10"
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 2000m
                memory: 6Gi

    service:
      main:
        controller: main
        ports:
          http:
            port: 5000

    ingress:
      main:
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
          cert-manager.io/cluster-issuer: internal-ca
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: "Spotify/YouTube Playlist Sync"
          gethomepage.dev/group: "Media"
          gethomepage.dev/name: "Syncify"
          gethomepage.dev/icon: "https://raw.githubusercontent.com/TheWicklowWolf/Syncify/main/logo.png"
        hosts:
          - host: syncify.internal
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - syncify.internal
            secretName: syncify-tls

    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: nfs-client
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /syncify/config
      downloads:
        type: persistentVolumeClaim
        storageClass: nfs-client
        accessMode: ReadWriteOnce
        size: 8Gi
        globalMounts:
          - path: /syncify/downloads
